const appnmae = "Agri shop Seller App",
      login = "Login",
      welcome = "Hi, welcome to",
      email = "E-mail",
      password = "Password",
      forgotPassword = "Forgot Password",
      emailHint = "eg. admin@gmail.com",
      passwordHint = "* * * * * *",
      popular = "Popular Products",
      rating = "Rating",
      unpaid = "UnPaid",
      shopSetting = "Shop Setting",
      logout = "Logout",
      messages = "Messages",
      totalSales = "Total Sales",
      dashboard = "Dashboard",
      products = "Products",
      order = "Order",
      save = "Save",
      featured = "Featured",
      edit = "Edit",
      editProfile = "Edit Profile",
      changeImage = "Change Image",
      remove = "Remove",
      setting = "Setting",  
      name = "Username",
      confirmpass = "Confirm Password",
      shopsetting = "Shop Setting",
      chats = "Chats",
      anyProblem = "In case of any difficulty, contact administration";


const nameHint = "eg. vender name",
      shopDiscHint = "Enter your shop Description",
      shopWebsiteHint = "eg. vendor.agrishop.com",
      shopMobileHint = "eg. +9121855150",
      shopAddressHint = "eg. Near Railway Bazar",
      description = "Description",
      mobile = "Shop Mobile",
      website = "Shop Website",
      address = "Shop Address",
      shopname = "Shop Name";
      
      
      
      